language: go

go:
  - 1.13

env:
  - GO111MODULE=on

before_install:
  - go get -t -v ./...
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.18.0

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  - go mod download
  - golangci-lint

after_success:
- bash <(curl -s https://codecov.io/bash)
